### ISSUE TITLE
Can fail to get random unused port

### ISSUE THREAD

**Issue by sneurlax** [cypherstack/tor#23]
See https://github.com/cypherstack/stack_wallet/issues/675 for example

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Failed to get random unused port!
#0      Tor.start (package:tor_ffi_plugin/tor_ffi_plugin.dart:110:9)
<asynchronous suspension>
#1      TorService.start (package:stackwallet/services/tor_service.dart:74:7)
<asynchronous suspension>
#2      main (package:stackwallet/main.dart:179:5)
<asynchronous suspension>
```

**Comment by Cyrix126** [comment]
potential fix ?
https://github.com/Foundation-Devices/tor/pull/67
